
DROP TABLE IF EXISTS Movie.Viewing;
DROP TABLE IF EXISTS Movie.MovieGenre;
DROP TABLE IF EXISTS Movie.Cast;
DROP TABLE IF EXISTS Movie.Movie;
DROP TABLE IF EXISTS Movie.Actor;
DROP TABLE IF EXISTS Movie.Genre;
DROP TABLE IF EXISTS Movie.ProductionCompany;
DROP TABLE IF EXISTS Movie.Director;
DROP TABLE IF EXISTS Movie.Customer;
DROP TABLE IF EXISTS Movie.CustomerCategory;